imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.mock_file
    profiler:
        collect: false

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true

security:
    firewalls:
        main:
            http_basic:

doctrine:
    dbal:
        default_connection: default

        connections:
            default:
                driver:   pdo_sqlite
                driver_class: ~
                path:     ":memory:"
                memory:   true
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        default_entity_manager: default
        entity_managers:
            default:
                connection: default
                mappings:
                    CelarisGameBundle: ~
                    CelarisSiteBundle: ~